apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
